### ISSUE TITLE
@ mentions don't work with usernames with dashes

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#1]
They don't! I can probably fix this but I'll have to relearn regular expressions first. Image is from my build of the site but I didn't touch anything related to @ mention pattern matching, so I think that this is present in the original as well.
![dash error](https://user-images.githubusercontent.com/49729978/56461182-816cda80-637c-11e9-8eaf-db842ea8dd31.jpg)

**Comment by lowercasename** [comment]
I'll for sure have a look at this - good catch.

**Comment by lowercasename** [comment]
Fixed in https://github.com/lowercasename/sweet/commit/570bdf1a4535fc13c8b34eb30abe18959d7f6752
