### ISSUE TITLE
If you try to go to a post you made in a private community you've left the server hangs

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#101]
Perhaps we should make an exception and let one see one's own single posts in even private communities that one has left so that one can click on the notifications that one gets about such posts? Or perhaps not, but I'm leaning towards perhaps

**Comment by lowercasename** [comment]
Yeah I guess? This was _vaguely_ intentional but now I think about it, it's also more than vaguely dumb, so probably should change it

**Comment by toBeOfUse** [comment]
Thy will be done. d0ed6f4
