### ISSUE TITLE
hm

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#102]
![Screenshot_20190508-125830~01](https://user-images.githubusercontent.com/49729978/60384963-0433a500-9a52-11e9-82a1-7579ceb81246.jpg)
hello there. shark

**Comment by lowercasename** [comment]
why are you.... showing me,,,, shark

**Comment by toBeOfUse** [comment]
because it's in an ad for digitalocean! if you look up the ip address that sweet.sh is attached to, that's the company that shows up. i assumed you were like their direct client for web hosting, but it sounds like the situation is more complicated somehow. also the shark is cute

**Comment by lowercasename** [comment]
oh i see! yeah sweet's on digitalocean, the nameservers are attached to another digitalocean instance which hosts the mailserver.
