### ISSUE TITLE
emailer not emailing :(

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#108]
Well I'm going the fuck to bed, but: this is the log file at the time of no email happening for @lowercasename:
![image](https://user-images.githubusercontent.com/49729978/60412861-d4df7e00-9ba0-11e9-824f-69dfecfae4aa.png)
and then there should be another line that says "email sent with [however many] unread notifications" but there isn't. Because it logged "sendUpdateEmail ran" that function must have indeed been called, because it's called 2 lines directly above [the line that adds that to the log file](https://github.com/lowercasename/sweet/blob/master/app/emailer.js#L106). And the only parameter it takes is the user object, which we know is set correctly because the correct username is there in the log file. So, that function is being called correctly, but it must be crashing, maybe check the error logs for that.

**Comment by toBeOfUse** [comment]
It's working fine for me btw, I set my email time to 2 minutes in the future and 2 minutes later got email. (Although it looks like cake.svg isn't loading, possibly blocked by gmail I think.) This is a really stupid question, but are you sure your sweet account was made with your current email address?
![image](https://user-images.githubusercontent.com/49729978/60413678-ba5ad400-9ba3-11e9-9fc7-56bf08e72245.png)

**Comment by toBeOfUse** [comment]
Added even more log writing to the emailer in the cleanup branch: 8f1f538. I don't think it'll help us right now but just on principle it should have been there in case something like this started happening.

**Comment by lowercasename** [comment]
It now worked??


________________________________

**Comment by toBeOfUse** [comment]
Yeah. Is the train cool?
![image](https://user-images.githubusercontent.com/49729978/60415598-9dc19a80-9ba9-11e9-896c-3092eddfa7be.png)

**Comment by toBeOfUse** [comment]
Is it a fast one? I was on a fast one once and it was great. And I was seated at, like, a table instead of uncomfortable airplane-seats style. Or is it a rickety old Soviet model

**Comment by toBeOfUse** [comment]
The only meaningful change I made to the actual emailing code was: now it passes a callback function to transporter.sendMail, in order to get the info object (displayed above) upon an email being sent. Previously, that area of the code called .catch() (which I think I put there) on sendMail, instead of passing this callback to the function like it does now (which will also deal with errors in addition to the info thing.) The docs are a little lukewarm on the whole returning a Promise thing (which is what .catch() was theoretically being called on) and focus on the callback method we're now using instead? Anyway, either that did something unexpectedly positive or our connection to the mail-sending server has just been unreliable in the past but worked this time (and also has for me every time I've expected an email.) Time will tell, but I'm optimistic!

**Comment by toBeOfUse** [comment]
![image](https://user-images.githubusercontent.com/49729978/60742906-2d19d580-9f3d-11e9-8203-79951df84f4f.png)

Hey, if you got this email at about 8:00am your time this morning (July 5 2019) I'm going to go ahead and consider this probably fixed and close the issue, maybe it is and maybe it actually isn't but I like closing issues ok
