### ISSUE TITLE
Notification alarm bell should not be hidden by default on mobile

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#11]
When I look at Sweet on my phone I don't usually realize that I have a notification until I hit the "open tabs" button to close the sweet.sh tab and see that the title of the tab has a (1) in it. I believe that this situation could be improved. Also, the placement of the alarm bell in the drop-down panel on the mobile site leaves a lot of distracting empty space to its right

**Comment by lowercasename** [comment]
See https://github.com/lowercasename/sweet/issues/12#issuecomment-486290849.
