### ISSUE TITLE
Maybe when someone posts a super wide image it should say to "click to view the whole thing"

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#110]
Right now it just cuts off the sides if it's any wider than the visible area here:

![image](https://user-images.githubusercontent.com/49729978/60452148-e43fe500-9bfb-11e9-9e9a-920e20940661.png)

And with no indication, I didn't realize the full image was wider for, a while. Or maybe we could just make it real short and people will want to click to make it bigger automatically?

![image](https://user-images.githubusercontent.com/49729978/60452106-d1c5ab80-9bfb-11e9-97bc-41a5bc7f3be3.png)

Idk. I've gotta stop noticing stuff like this whilst I remain bad at CSS

**Comment by lowercasename** [comment]
I mean this straight up shouldn’t happen, it should work the second way always - I will take a look at it... soon


________________________________

**Comment by toBeOfUse** [comment]
To get the second screenshot I had to trial-and-error uncheck height:100%; on the img and then go two levels up and uncheck display:grid; on the containing div, if that helps, I'd probably have to spend a while reading about CSS grids to make any sense out of how the current height is being arrived at

**Comment by toBeOfUse** [comment]
Also this does only happen in Chrome and not Firefox, which must have been where you tested this, I just checked

**Comment by toBeOfUse** [comment]
Ok, it looks like the problem was how Chrome handles the "auto" setting with regard to image width, which it apparently does just by making them real wide (and thus in this case cropped on the sides), at least within a grid layout (?), and it was happening in two places. First, when grid-template-rows was set to 100% with no set grid container height for it to be 100% of, it decided that 100% meant "auto." I fixed this by setting explicitly setting grid-template-rows to "min-content," which makes rows as short as is possible without messing with their contents, which is what we want. Also, width: auto; was set on the image itself, which, again, made Chrome want it to be real wide, so that's gone and instead single images have object-fit: contain; set to enforce the sizing behavior that that was supposed to be enforcing. (Images in multi-image posts are still object-fit: cover; like you had it originally.) This "CSS" stuff! I just don't know.
