### ISSUE TITLE
There probably should be a "someone replied to your comment specifically" notification

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#112]
To go along with the new threaded comments system. Right now you just get "someone replied to a post you also replied to” or "someone replied to your post," depending obviously on whether it's your post or not, both of which won't show up for unsubscribed users, and I kinda wonder if direct replies to one of your comments should actually give you a notification whether you're unsubscribed to the post or not, like @ mentions currently do. ALSO, please don't take this the wrong way, but I kind of want to make a notifier function that's just used like notifier.notifyV2(notificationText, notificationImage, url) and start using it wherever possible, the current notifier function I'm sure made good sense at the time but it's getting a little long and the parameters it takes are kind of confusing

**Comment by lowercasename** [comment]
I'm 100% all for a new notifiier API, I guess it might make it a bit harder to keep standardised but way easier for us to read!

**Comment by lowercasename** [comment]
This has currently been implemented in https://github.com/lowercasename/sweet/pull/117/commits/978b71ef41503147647428cbbee13923c482391e but with the old notificication API for now
