### ISSUE TITLE
Colorz

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#114]
![image](https://user-images.githubusercontent.com/49729978/60749981-104ac580-9f70-11e9-8cf7-9c278a917016.png)
This is every unique color in style.css. We could standardize these maybe, carefully pick a few specific shades of grey and find-and-replace until they're the only ones there. This probably should be part of a dark mode/styles.css cleanup pull request. [Here's](https://pastebin.com/RDcjZPVs) the pastebin that has these colors in copy-pasteable form.

**Comment by toBeOfUse** [comment]
[Here's](https://pastebin.com/AF5bk4vQ) my quick attempt at creating a more organized list, turns out there's no particularly meaningful way to sort colors but you can kind of see which greys blend into each other here. The colors with transparency are grouped at the top of the list bc the transparency might be important, I'm not sure where those are used though so I don't know how.

![image](https://user-images.githubusercontent.com/49729978/60750418-0035e480-9f76-11e9-8e11-ab8bc6b904a0.png)

**Comment by toBeOfUse** [comment]
The problem with visual design is that whilst one does it, one starts to have _thoughts_ about aspects of one's design until sooner or later one lives in a mental world where it makes perfect sense, as long as you're looking at it entirely with your forebrain, whereas everyone else that comes along is going to be looking at it entirely with their hindbrain (yes, I am a brain scientist) and their instinctual sense-perception is going to be different from how the designer had been thinking about it 9 times out of 10. Abstract thought is all well and good in moderation, but sooner or later it ought to be put in a communicable form and that's going to require outputting a feeling, that's as commonly felt by everyone as can possibly be arranged, as opposed to just understandable within a mental world in which associations have already been slowly built up...  I've gotten completely used to the orange comment-on headings but I don't want to forget that my immediate hindbrain reaction to them was a small feeling of alarm. Probably not like for everyone, hindbrains are not all identical, it's not like... no design is just the sum of its parts, if you focus on stuff that you consciously observe then you stop noticing the stuff that subconsciously has an effect on you, if you cultivate too many thoughts about the parts in your forebrain then the hindbrain is blocked from seeing the whole. Anyway, I guess it would be cool to add more, like, colors, those are neat

**Comment by toBeOfUse** [comment]
[Codepen for the ordered colors display list](https://codepen.io/anon/pen/ydxEMd), that probably makes sense. I was trying to accomplish something like this when I pulled all the colors out and put them at the top of the css file way back when, but I wasn't familiar enough with regex back then to see this possibility, this should hopefully help the dark mode thing \*finally\* get done...

**Comment by lowercasename** [comment]
So I would say that this is good and valiant work, but to do it properly we need to rip Bootstrap kicking and screaming out of our code. We need to standardise a set of colours, HTML element styles, and positioning styles (which need not be universal like Bootstrap’s, they can rely on the positioning of specific elements in relation to each other). We also would need to rename most elements on the site - my ideal here is to use classes where possible in lower case with dashes, and use IDs, also in lower case with dashes, for things like unique buttons that have associated JavaScript. This is a big job I don’t think I’ll be able to undertake until at least September, PhD dependent - but as it stands style.css is a horrific mess full of unused and misapplied styles which cancel each other out. We should also, in doing this, transition to a modular scss setup with a precompiler, which I don’t have much experience with.
