### ISSUE TITLE
i did this weird styling thing and i'm kinda into it?

### ISSUE THREAD

**Issue by lowercasename** [lowercasename/sweet#118]
![Screenshot 2019-07-07 at 18 52 26](https://user-images.githubusercontent.com/1748384/60772061-722e3b00-a0e8-11e9-9568-29ffdf8749b0.png)

obviously I need to get these styles out of Firefox Developer Console and into a PR but in the meantime... I feel like this makes the site brighter, friendlier, easier to read, easier to distinguish individual posts, easier to see where comments are and to which parent comments they belong.

????

**Comment by lowercasename** [comment]
The only thing I'm not sure about is maybe the whole reply form needs to be in a grey bubble of its own?

**Comment by toBeOfUse** [comment]
This is good! I like the separations. Yeah, I think it makes sense to wrap the reply form in something. The only other thing is that I feel like the username is a little disconnected from the comment, at first glance? Maybe they could be pushed closer together or something

**Comment by lowercasename** [comment]
Implemented in https://github.com/lowercasename/sweet/pull/117
