### ISSUE TITLE
On mobile, notifications go off the bottom of the screen and do not scroll

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#12]
So, either load fewer notifications or put them in a little scrollable text element of their own that's sized not to go off the bottom of the screen. (On larger screens this element would automatically not scroll because it would be able to match its size to the size of the content (the notification list) that it's displaying, making scrolling unnecessary.)

**Comment by lowercasename** [comment]
I was wondering if on mobile there should be a dedicated notifications page, a la mobile Facebook or mobile Twitter. I don't love the FontAwesome standard collapsing menu for sweet anyway - I think I could make a dedicated mobile set of icon-only links and have a mobile-only Settings and Log Out button probably on the profile page, or heck right in the menu bar - this would also resolve the notifications not visible on mobile problem, which equally irks me.

**Comment by lowercasename** [comment]
I've fixed this in the latest commit with an overhaul of the mobile menu - should be much better.
