### ISSUE TITLE
Relative links to tags and mentions in posts now try to open as external links

### ISSUE THREAD

**Issue by lowercasename** [lowercasename/sweet#120]
This appears to be connected with code in the sanitiseHtmlForSweet function which adds '//' to links - I'm not quite sure what it does! Don't want to mess with it in because it's presumably got a useful purpose.

**Comment by toBeOfUse** [comment]
It's a fair cop. The // is added to fix issue #106 - but I didn't see that links for @ mentions and hashtags would get caught up in it as well. (Although I phrased it in that issue title as "adding http", adding // works just as well to tell the browser that a link should be external and doesn't look wrong when applied to links to sites that are actually https.) The solution is just to not add the // if the link already starts with a /.

**Comment by toBeOfUse** [comment]
I committed this fix directly to master because it's so small: b983bb1
