### ISSUE TITLE
Video embeds aren't rendered in comments

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#121]
If comments aren't supposed to be allowed to have embeds in them, then helper.parseText should be called with the youtubeEnabled parameter set to false, to keep the video url from being eaten because of the assumption that a video link preview will be rendered to replace it. Otherwise, the comment schema should have an embeds field in it and that should be used to render the embeds in the comment and comment_dynamic handlebars files.

**Comment by toBeOfUse** [comment]
My guess is that you don't want video embeds to work in comments, so I've pushed another tiny commit to master (9633200) that stops the embedding code from working at all in them, which stops video urls from being vanished out of there with no replacement. (Either way it's a quick fix that'll stop anyone from being completely surprised by what happens in this case.)

**Comment by lowercasename** [comment]
Oh no!! I forgot about comments because I a dork! No I actually absolutely would like video embeds in comments, I’m so sorry


________________________________
