### ISSUE TITLE
Post controls can go off the side of the screen on small phones such as iPhone 5/SE

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#126]
I suppose some of those are still out there. Each post control element is 40px wide with 32px of right margin, and with 5 showing up on a user's own post that does this on a screen that's that small:

![image](https://user-images.githubusercontent.com/49729978/61405134-0ba6db00-a8a7-11e9-917b-90136c42d0f0.png)

**Comment by lowercasename** [comment]
I believe this is fixed in the last batch of CSS edits!
