### ISSUE TITLE
Tags in posts in public communities should come up on tag search pages

### ISSUE THREAD

**Issue by lowercasename** [lowercasename/sweet#128]
I can’t actually remember how it works currently but tags should be an easy way to find related posts across all of sweet, including in public communities - and honestly if you’re a member of a closed community those posts should come up as well in the tag search page. That’s an opinion though - what do you think??

**Comment by toBeOfUse** [comment]
Tagged posts from public communities do appear to show up on their tag pages, as well as tagged posts from any private communities that you are a member of, which does in fact make complete sense to me, go team
