### ISSUE TITLE
/resend-token does not resend email verification tokens

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#13]
I don't think this function was finished? It never actually calls sgMail.send()

**Comment by lowercasename** [comment]
That's hilarious, it looks like I overwrote the actual code which did send the email with the fake code which only pretends to send an email, after I was done testing. Go me! Will have to fix soon.

**Comment by lowercasename** [comment]
Should be fixed in https://github.com/lowercasename/sweet/pull/16/commits/b3dd4633c82e01c07770c3b6ef6d6e8d4daa382b
