### ISSUE TITLE
I can't scroll down to the submit button in the profile editor on mobile

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#132]
![Screenshot_20190729-200246](https://user-images.githubusercontent.com/49729978/62090894-8aebc580-b23c-11e9-9221-29d8b5e2f6a2.jpg)
This is as far down as I can get it to scroll. Also, this is kind of niche, but when you click "request desktop mode" to try to get around this problem, link preview images are a bit off:
![Screenshot_20190729-200552](https://user-images.githubusercontent.com/49729978/62090931-b8387380-b23c-11e9-987f-70a0e166c7d4.jpg)

**Comment by lowercasename** [comment]
Pretty sure the first thing is fixed here: https://github.com/lowercasename/sweet/pull/136/commits/faf581d5e4f1767a850aafd32596ea9f37d831ee
