### ISSUE TITLE
Verification tokens last for 12 hours but the emails containing them say they last for 1 hour

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#14]
The token expiration code in passport.js looks like this:
`newUser.verificationTokenExpiry = Date.now() + 43200000; // 12 hours`
but the email says that "The token will expire in an hour." Although password reset links last for one hour and also correctly say that they do in the email.

**Comment by lowercasename** [comment]
Should be an hour, well spotted.

**Comment by lowercasename** [comment]
Fixed in https://github.com/lowercasename/sweet/pull/16/commits/b3dd4633c82e01c07770c3b6ef6d6e8d4daa382b
