### ISSUE TITLE
Navbar and send form buttons are too small on mobile 

### ISSUE THREAD

**Issue by lowercasename** [lowercasename/sweet#144]

**Comment by toBeOfUse** [comment]
well, i made them about the same size as the keys on my phone keyboard,
which i'm pretty used to. there's barely enough room there as it is when
private is displayed. maybe two rows of buttons, then?

**Comment by toBeOfUse** [comment]
![IMG_20190821_023415](https://user-images.githubusercontent.com/49729978/63408140-54791480-c3bc-11e9-8584-80916fd604fa.jpg)

**Comment by lowercasename** [comment]
Hm, good point, my screen is a little bigger. I just swear they were larger before. Maybe it’s fine then!

**Comment by toBeOfUse** [comment]
Yeah, they were larger, I had to shrink them to fit the link preview button
and the draft option. (On iPhone SE the text labels for the post privacy
selectors are hidden now to make it all fit, hopefully iPhone SE owners are
good at interpreting eye- and pencil and ruler-based symbols)
