### ISSUE TITLE
Out of memory errors

### ISSUE THREAD

**Issue by lowercasename** [lowercasename/sweet#149]
So node is crashing with out of memory errors, with three spikes in CPU usage, disk I/O, and bandwidth correlating to the three times the server restarted in the last 8 hours. Why? I have no bloody idea. I've put some logs on the server:

https://sweet.sh/error_2019-08-20.txt is for 2019/08/20 (and isn't interesting although does have an error)
https://sweet.sh/error_2019-08-21.txt is for 2019/08/21
https://sweet.sh/error.txt is the latest log, which hasn't been logrotated
https://sweet.sh/out.txt is the latest out log, and we really should turn down the verbosity for the prod environment, huh

I thought the out of memory errors are something to do with image uploads, since they seemed to happen when I tried to upload an image, but I can't see any indication of that in the logs. Also it would be fantastic if they had timestamps. Alas, no.

**Comment by lowercasename** [comment]
There's password data in the output log so uh, I will delete him lol

**Comment by toBeOfUse** [comment]
If it was hashed, you really don't have to worry about it, if it wasn't
then I'm concerned

**Comment by toBeOfUse** [comment]
Oh, you mean your server passwords?

**Comment by toBeOfUse** [comment]
Thanks for the logs, I'll look it that in a few hours when I'm back at my
computer

**Comment by lowercasename** [comment]
No, I meant hashed user passwords, but also full profile data and stuff :shrug:

**Comment by toBeOfUse** [comment]
I'm trying my damnedest to upload enough images to run my computer out of memory but it's not happening

**Comment by lowercasename** [comment]
Yeah so it's stopped happening for me as well. What

Could have been a one-time thing, I'm aware that's not how code works but... shush

**Comment by lowercasename** [comment]
I've set up a >70% for 5 minutes memory usage email alert as well

**Comment by toBeOfUse** [comment]
Is there no log like this stored on the server that would tell us what requests were made right before it went down? Was that in out.txt somewhere?
![image](https://user-images.githubusercontent.com/49729978/63460990-a7d37d00-c425-11e9-8f86-9e4e0b041725.png)
I believe that log is written to the standard output by morgan. It's not timestamped, but you can see when the server had to restart by looking at the body-parser deprecated warnings that are printed when that happens

**Comment by lowercasename** [comment]
Okay both out logs are now online at out.txt and out_2019-08-21.txt!

**Comment by toBeOfUse** [comment]
Ok, so all three after-crash reboots are visible in out.txt, findable by the "the magic happens on port" message. The first reboot is on line 12668; the previous image uploading request is on line 12416. The next is on line 15848; the previous image uploading request is on line 15742. The last is on line 16321; the previous image uploading request is on 16231. I'm not sure if this constitutes a connection; with 19 image uploading requests and 24422 total lines, on average they should be like 1200 lines apart; the fact that the crashes had image upload requests "only" 100-200 lines before them each time is suspicious but could be coincidental.

**Comment by toBeOfUse** [comment]
The spikes in CPU usage and disk i/o around the time of the crashes could just come from the server booting up, but the bandwidth spike seems pretty weird - something has to be making requests for that, right? In the patch pull request I'm going to add a thing to have morgan log request timestamps right alongside the urls and stuff that are in the logs that you've posted.

**Comment by toBeOfUse** [comment]
well, fuck me, by default morgan doesn't log requests until after the
server responds to them, so if a specific request crashed the server it's
automatically just Not In There, bc, the server crashed. very helpful
morgan, great job

**Comment by toBeOfUse** [comment]
a 24,422 line log file and it skips the three requests we would potentially actually want to see by default

**Comment by toBeOfUse** [comment]
i have smoke coming out of my ears right now

**Comment by lowercasename** [comment]
This is hilarious and I am sorry about technology


________________________________

**Comment by lowercasename** [comment]
Sadly after some investigation it turned out that the technology was the only technology we had


________________________________

**Comment by lowercasename** [comment]
technology.horse

________________________________

**Comment by toBeOfUse** [comment]
technology.fuckyou

**Comment by toBeOfUse** [comment]
All logging will look like this from now on:

![image](https://user-images.githubusercontent.com/49729978/63476834-9e133f00-c450-11e9-9835-07da3b604020.png)

Sample error log:

![image](https://user-images.githubusercontent.com/49729978/63477152-d9623d80-c451-11e9-9a90-0cb687a26618.png)

Note the timestamps and the fact that the requests don't show the response code at the end (200, 304, 404) because they're logged immediately instead of waiting for the response to happen. The morgan output (the lines for the specific get and post requests) still won't show up in the debugger because I've decided it doesn't need to. It would take about 18 more characters in server.js to also log the username of the user making each get and post request, but that's probably too invasive at the moment.

**Comment by toBeOfUse** [comment]
Also, I'm having the Morgan full request log output to a separate file, like "full request log starting [timestamp].txt". This isn't to dismiss it, if the server runs out of memory again I think that the last line of that file should be the first thing you look at, to see what the last request that was made to the server before it crashed was, but it is a bit verbose to have that mingling with the regular console.out stuff all the time. If you're definitely setting NODE_ENV to "production" when you start the actual server, maybe it should also only bother outputting anything if that is true, I've never used it during development much.

**Comment by lowercasename** [comment]
Okay it's happened again! I wrote a post and uploaded a photo I'd just taken on my iPhone from my iPhone. It got to 100% and then hung on uploading. When I refreshed the page, nothing was loading, including my other sites on the same server box, and I couldn't SSH in. After about five mintues the sweet process reloaded, and it doesn't take down the whole server (which is nice), because my server hasn't actually restarted in 111 days.

In the out log, all we have (after a notification that a previous post of mine sent a notification):

`[25/08 16:03:48.228] Server booting on default port: 8686`

In the error log, nothing useful: an error message from the 22nd, and the normal warning messages as the process starts up again.

**Comment by lowercasename** [comment]
I then tried uploading the photo again and it went off without a hitch.

**Comment by toBeOfUse** [comment]
amazing. what about the other out log, the really long one? it should be at
the app root directory (next to server.js) with a timestamp in the name and
like "request log" or something. the most recent one will have roughly the
same timestamp as the "server starting up" message and then the end of the
one before that should show the activity right before the crash

**Comment by lowercasename** [comment]
u hate 2 see it

```
[25/08 16:01:12.894] get request for /community/sweet-and-sorcery
[25/08 16:01:14.390] get request for /showposts/community/5ca104482728f01ac8ce9eb6/1566748874343
[25/08 16:01:14.596] post request for /api/user/followers
[25/08 16:01:14.644] get request for /api/notification/display
[25/08 16:01:15.009] get request for /api/image/display/zFgQ38AkP.png
[25/08 16:01:15.069] get request for /api/image/display/INVzbk-y4.png
[25/08 16:01:15.073] get request for /api/image/display/XqcneYDDG.jpeg
[25/08 16:01:15.075] get request for /api/image/display/yXz4O7L6l.png
[25/08 16:01:15.075] get request for /api/image/display/EC8DI33po.png
[25/08 16:01:15.075] get request for /api/image/display/GsEf_KE3i.jpg
[25/08 16:01:18.386] get request for /heyaretherenewposts/1566748818361
[25/08 16:01:18.514] get request for /api/notification/display
[25/08 16:01:37.487] post request for /api/image/v2
```

**Comment by toBeOfUse** [comment]
Well, that kinda does narrow it down, then, to something that happens when
an image is uploaded. The weird thing is that it only happens some of the
time, and when it happens doesn't seem to depend on the specific image
that's being uploaded. Can we assume that the specific request is causing
the out-of-memory error, rather than being like the last straw for a memory
problem that was already happening? Based on how you mentioning last time
that memory usage spiked, it didn't just build up?

**Comment by toBeOfUse** [comment]
This is an extremely low-effort and probably unhelpful suggestion, but I
guess the version of Sharp currently used by Sweet is 0.22.0 and it could
be updated to 0.23.0

**Comment by toBeOfUse** [comment]
![image](https://user-images.githubusercontent.com/49729978/63655636-8d1c4380-c758-11e9-9141-eecbcbcace59.png)

See, what I've been thinking about is this addition to the codebase as of the new post editor pull request, where sharp generates a thumbnail version of your image and stores it in an object in memory, for retrieval by the client so it can use a small image in the preview in the editor - this removed a lot of lag from my tests of the editor on my phone, because it didn't have a huge image to scale down, display, and potentially move around. Beats me how it could possibly be causing this error, though; the thumbnail that's stored in memory is, as you can see, 200 pixels tall at most, and is deleted from memory within 30 seconds; and also, it makes no sense that it would only cause a problem some of the time. It could certainly be removed though, plain and simple, and then we could see if the out of memory errors stop. The client-side code wouldn't even need to be changed, it already makes sure the thumbnail is available before trying to use it, the only thing that would need to be taken out is exactly the code I've screenshotted above, I believe.

**Comment by toBeOfUse** [comment]
that starts on line 85 of viewingSweet.js, btw

**Comment by lowercasename** [comment]
Yeah as much as I'd love to ascribe this to some of the documented memory leak problems in sharp, i just don't think this is a leak of that kind:

<img width="956" alt="Screenshot 2019-08-25 at 23 46 59" src="https://user-images.githubusercontent.com/1748384/63656922-cffb0d00-c792-11e9-9a75-d6697c067703.png">

What I will say is that it looked like the thumbnail thing was the issue because the JS seems to hang at the point where it's trying to retrieve the thumbnail back into the frontend.

**Comment by lowercasename** [comment]
Let's try updating Sharp first and see if that helps? It does seem to happen reasonably regularly so it won't take that long to diagnose, hopefully

**Comment by toBeOfUse** [comment]
HUH. So your graphs are on British Summer Time, not GMT/UTC like the log timestamps/internal server clock are. Is it a stupid question to ask why the memory graph itself has no spike and in fact never seems to approach 100%

**Comment by toBeOfUse** [comment]
I don't know about the other log files, but the email log says that the server's booted up twice on August 25th:
![image](https://user-images.githubusercontent.com/49729978/63658699-b1891780-c77a-11e9-8e74-91dd2b2922df.png)
![image](https://user-images.githubusercontent.com/49729978/63658705-b948bc00-c77a-11e9-97bd-cb207433f8d9.png)
The correspondence between those times and the ones that have spikes on the graph is a bit loose, doncha think
![image](https://user-images.githubusercontent.com/49729978/63658768-35db9a80-c77b-11e9-926b-7281a8cd8dee.png)
(Graphic design is my passion.) The spike occuring at 5 pm on the graph matches up with the server starting up at 4:03 pm if the graph's times are in British Summer Time and the server is on UTC (which it is, I believe) but I have no ideas that explain the difference between the 10:21 am reboot on the email log and 7:30 am ish spike on the graph.

**Comment by toBeOfUse** [comment]
See #160 for now
