### ISSUE TITLE
Immediately after you sign up, you're logged in, pre-email verification

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#15]
If you go from the page that's like "thanks, we just send you an email verification email" to the home page or a specific user profile you can see every profile and follow and trust users just like you're logged in, even though if you try to actually log in it will tell you you can't because you're not verified.

**Comment by lowercasename** [comment]
I think changing newUser to false on line 124 in passport.js might fix this, though I can't test it now. It might also create other problems - the core login and registration script is mostly from a tutorial and I therefore don't know how some of it works. :-\

**Comment by toBeOfUse** [comment]
Yeah, it looks like that fixed it. It's not immediately clear to me why the signup function is a passport strategy at all right now instead of just another app.post() thing, given that it never results in actual authentication?
