### ISSUE TITLE
Don't try and fix code when you don't have access to a real SSH terminal

### ISSUE THREAD

**Issue by lowercasename** [lowercasename/sweet#150]
I merged your lightning fast pull request and also an attempt at fixing a bug showing a single post with a link preview (I think the 'images' property it's trying to fetch doesn't exist?) but also now I appear to have done something real weird in GitHub (merged master into master??), I am very sorry

I think the single post bug is persisting but I'm just leaving this alone until I'm at an actual computer, really I should be writing my PhD

**Comment by toBeOfUse** [comment]
you merged your master branch into mine and then mine into yours, that part
is fine, i did note an actual problem though in the comments just now

**Comment by lowercasename** [comment]
there is nevertheless a lesson in here about the fact that a QEMU console on DigitalOcean and a phone are not a replacement for SSH access and a local development version of your code

**Comment by lowercasename** [comment]
i discover so much in my short time learning from you, and yet i go so wrong

**Comment by toBeOfUse** [comment]
to be fair i don't really know what an ssh is. i have a vague memory of an
xkcd where the guy used it to make text to speech happen on an inside
computer to try to get his roomate to let him in

**Comment by toBeOfUse** [comment]
or what a qemu is for that matter. does the emu stand for emulator or does
it mean the tall bird

**Comment by lowercasename** [comment]
yeah that's all it is, i make the computer in the server room yell at a technician, he opens whatever files we need to change and i just tell him what line to go to and what to write, it takes hours

**Comment by lowercasename** [comment]
qemu is an emulator that in DigitalOcean's case runs my Linux virtual server on, uh, more Linux. it also provides an command line emulator which is the only way I can get into my server from this laptop because I refuse to give it public key access to my server, to prevent me from spending all day coding, except you see I worked out the QEMU console thing, except you see I definitely won't be doing that again

next collaborative project: emulate an emu in qemu

**Comment by toBeOfUse** [comment]
Your master branch should be good now, I think I've got that metadata
glitch fixed, good catch on that
