### ISSUE TITLE
Ok I guess the site just crashes whenever I try to upload a picture of a dog

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#156]
This is really small and I should probably just go and fix it instead of making a report about it but instead I'm trying to get my post editor codepen demo working in Microsoft Edge for some reason. Turns out Micrsosft Edge sucks

**Comment by lowercasename** [comment]
Oh jeez yeah I have honestly never even tried running sweet in Edge. How... is it


________________________________

**Comment by lowercasename** [comment]
Well that puts paid to my theory that it was iOS-specific…

**Comment by lowercasename** [comment]
Oh no, how could we fail endless.horse in this way?

Yeah it looks like it's back up now on my other sites... so could there just be a general problem with sharp?

**Comment by lowercasename** [comment]
Okay I've updated sharp to 0.23 and it appears to work fine from a quick test, I'm putting that up on the production server

**Comment by lowercasename** [comment]
It's up!

**Comment by lowercasename** [comment]
The dog is _so beautiful_, I don't understand how she can be anything other than a blessing

**Comment by toBeOfUse** [comment]
Going to #160 for out of memory issues for now
