### ISSUE TITLE
Should the "edited" marker show up for edits made less than ≈2 minutes after posting

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#157]
Said marker shows up on most every post now but when you hover over the thing to see the timestamps it generally says something like posted: 4:30 pm, edited: 4:31 pm. Idk if there's a point to displaying it in such cases

**Comment by lowercasename** [comment]
I guess it's easiest to leave it as is? Like... I don't mind either way it just saves us writing two more lines of code
