### ISSUE TITLE
Ctrl-S to save editor contents as draft?

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#158]

**Comment by lowercasename** [comment]
Perhaps we could enable to 'you've done shit in a text field do you want to not leave' API instead? I think it could be quite useful here. Ctrl+S to save isn't used in other places online and honestly is used less and less on PCs too so may be a bit confusing.

**Comment by toBeOfUse** [comment]
That's a good idea. It would be nice if it could explicitly offer the user
the option to save post box contents as draft when leaving the page but
browsers don't seem to like to offer much control over page closing these
days. It certainly could auto-save post box contents as draft when the
window is closed but, no, probably not, might be confusing since there's no
way to signal what's happening there
