### ISSUE TITLE
Node.js memory usage is just arbitrarily limited it appears

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#160]
I don't think the server itself is running out of memory, especially considering this graph that you posted:
![image](https://user-images.githubusercontent.com/49729978/64480171-fb1d2d80-d190-11e9-810a-5d2e951f8a51.png)
The other graphs are spiking, presumably because of the work they have to do to restart the server process after it goes down, but the memory usage doesn't actually look excessively high, at least not from the server's perspective. According to [this](https://medium.com/@ashleydavis75/node-js-memory-limitations-30d3fe2664c0) and some other stuff you can google, Node.js just arbitrarily restricts the amount of memory it can use, and displays an out-of-memory error message when that amount is exceeded, even if there's plenty of memory available on a hardware level; a command line argument has to be used to override that, like `--max-old-space-size=4096` (for 4gb.)

**Comment by toBeOfUse** [comment]
The reason that this whole thing happens on the actual server but not on either of our regular computers may be because the default permissible memory usage level can be set by the environment variable, `NODE_OPTIONS`, which comes from ?????

**Comment by toBeOfUse** [comment]
I still don't know what ssh is and to be perfectly honest I have no plans to learn but I keep crashing the server many times with very good image uploads like the following and am very curious if you could find out if connecting in with it and running the server like `node --max-old-space-size=4096 server.js` would be as easy and fun as it sounds
![image](https://user-images.githubusercontent.com/49729978/64482228-91664900-d1bb-11e9-8c7b-019e05d8a75f.png)

**Comment by lowercasename** [comment]
Gonna try this tonight, great investigative work! If there aren’t any memory leaks in sharp, raising the memory threshold could just solve it


________________________________

**Comment by lowercasename** [comment]
He _thicc_

**Comment by toBeOfUse** [comment]
i assume that you are referring to the dog? her name is snoot-snoot

**Comment by lowercasename** [comment]
I primarily meant the server's max memory setting, but also snoot-snoot, hello what a good boy

**Comment by toBeOfUse** [comment]
I just uploaded that one dog picture that was consistently crashing the server earlier and successfully saved it as a draft three times in a row, so I'm going to go ahead and declare victory here! Annoying that this was even a problem in the first place, but at least it was eventually easy to solve
