### ISSUE TITLE
Emails sent for mention notifications are missing the user's username

### ISSUE THREAD

**Issue by lowercasename** [lowercasename/sweet#164]
I had a ten-second look at this which is all my PhD currently allows me and I can't work out why it's happening, user.username is used elsewhere just fine. Is it a bug in the template?

**Comment by lowercasename** [comment]
Datums:

![Screenshot from 2019-09-16 18-13-51](https://user-images.githubusercontent.com/1748384/64978593-c7878500-d8ad-11e9-9792-a2d02566a9dc.png)
![Uploading Screenshot from 2019-09-16 18-13-47.png…]()

**Comment by toBeOfUse** [comment]
It's a bug I introduced in the notifier, user.username in the emailer refers to the user who is receiving the email, you, and your username is indeed showing up, but the mentioners name isn't getting added to the text in the notification like it should. A one-line fix

**Comment by toBeOfUse** [comment]
1050640
