### ISSUE TITLE
How do I... start sweet

### ISSUE THREAD

**Issue by lowercasename** [lowercasename/sweet#181]
Whoops. I did not realise so much had changed, I've pulled the latest version to the server and run an npm update but am getting an error now:

```
Error: Cannot find module 'vue-loader/lib/plugin'
```

The script I'm running is 'npm run start'.

**Comment by toBeOfUse** [comment]
The linting PR @wlonk created also switched us to "yarn". Running "yarn
install" after the npm update should make it then work, hopefully

**Comment by toBeOfUse** [comment]
Then, start it with "yarn start"

**Comment by toBeOfUse** [comment]
If yarn wasn't installed by npm, then
https://classic.yarnpkg.com/en/docs/install is the best bet I guess. I
actually forget what I did to install it

**Comment by toBeOfUse** [comment]
At least on my machine, installing yarn, running "yarn install" and waiting
a bit, and then running "yarn start" does start the server, using the
current lowercasename/sweet/master branch of the code, so that's as much as
I can help from here, sorry

**Comment by lowercasename** [comment]
That's okay! It's still spitting out that error, so I'm currently upgrading yarn and we'll see how we go from there.

**Comment by lowercasename** [comment]
I'm now getting:

```
yarn start
Syntax Error: Expected "$", "$(", "${", "&&", "'", ";", "<", "<<<", ">", ">>", "\"", "\\", "|", "|&", "||", [ \t], or end of input but "&" found (line 1, column 19).
```

This might be an issue with the node binary which is loading this file?? I don't really understand much about this so I'm poking about in the dark...

**Comment by toBeOfUse** [comment]
A truly stunning error. One for the ages

**Comment by lowercasename** [comment]
Isn't it great? I think it's decided Javascript is broken

**Comment by lowercasename** [comment]
Which is, if nothing else, audacious

**Comment by toBeOfUse** [comment]
Line 1, column 19 of... what? It might be worth deleting the node_modules folder and `yarn install`ing that stuff completely from scratch in case the problem is in there

**Comment by toBeOfUse** [comment]
In any case, it's late here and I'm off to bed, good luck

**Comment by lowercasename** [comment]
Yeah I've made a new git clone and am trying with that now

**Comment by lowercasename** [comment]
Thank you! <3

**Comment by lowercasename** [comment]
Okay I've reverted sweet to the last commit before the switchover to Yarn and all the linting and for the moment I am just going to... let it be

**Comment by lowercasename** [comment]
I think at this point what sweet needs is its own server instance rather than running on a server with a dozen other websites

**Comment by wlonk** [comment]
@lowercasename I'd love to talk deployment strategies, if you want. Would a real-time-er way of talking be helpful? And I'll try to help debug your yarn situation, too.

**Comment by toBeOfUse** [comment]
![feb01e38-931a-488a-8da0-9182b168a46f](https://user-images.githubusercontent.com/49729978/75703622-cee8f200-5c85-11ea-99ba-69058df2fca5.png)

**Comment by wlonk** [comment]
Yessssss but also to take this too seriously, _communicating_.

**Comment by toBeOfUse** [comment]
This should have been blindingly obvious but in my defense it was pretty
late last night. I'm on my phone and don't have package.json open, but I'd
bet my net worth, both because I'm confident and because it would be
interesting to find out what happens when you bet a negative net worth,
that on column 19 of the "start" script therein there's an ampersand
character that's understandable to my machine, which uses Windows
Powershell to execute terminal commands, but not to whatever terminal
that's used by whatever operating system the Sweet server runs. The
solution would be a) changing the script so like, the actual server can
function and b) maybe having alternate versions of the starting scripts for
different OSes? Would be great if that could be detected automatically
somehow? Idk

**Comment by toBeOfUse** [comment]
I was right about the ampersand being on column 19 (and line 1, of 1) of the start script in package.json, so the error mesaage must have been complaining about that, but I'm still confused as to why it's suddenly apparently a problem, given that an ampersand has been there since [this commit](https://github.com/lowercasename/sweet/blob/391e4ffbed999fcf3df8ce123f085cd1b932040e/package.json) back in August

**Comment by lowercasename** [comment]
You two are lovely <3

Okay so as fortune had it, my work has told me to go play with their AWS instance. I've set up sweet from the most recent commit and it worked first time with no problems, so it's clearly an issue with my current server (*sad yay*): http://52.56.206.32/

There are a bunch of things I need to set up before transferring the domain over - namely SSL and configuring data (i.e. image) and database storage both sitting somewhere I control. I can use an mLab sandbox for free to store all 3.9MB of sweet's database (aww), and perhaps a very cheap S3 instance of my own for images. @wlonk, I would love your feedback on this option, and I would be delighted for a more real-time way of chatting, you can email me or add me on Facebook (Raphael Kabo)! **...or we build chat into sweet.**

With the current rewrite of the image schema ongoing, should I wait up before making this server transfer, especially because it would involve changing filepaths on a development version of sweet? Or will nothing in that affect the way we currently store images? It would also be bloody lovely to be able to get rid of the older way of storing images (public/images or public/uploads, I think?) and just combine that all into - currently - the cdn/ folder, and ultimately into S3 or something.

**Comment by toBeOfUse** [comment]
@lowercasename It would be doable to get rid of the old way of storing post images, sure (those old images are in `/public/images/uploads`; I'll add something to the script to move the post images that are in there out of there and create image database documents for them.) Do you want to move the user profile pictures and community display images into the cdn folder as well? And then ultimately into S3 or something? It would require a little more work to also generate Image documents in the database for those

**Comment by toBeOfUse** [comment]
@lowercasename Also, that IP address link currently yields but a 502 Bad Gateway error for me, jsyk

**Comment by lowercasename** [comment]
Okay everything is fine now, I have learned how to 'server'

**Comment by wlonk** [comment]
@lowercasename hurrah servering!
