### ISSUE TITLE
Problems sending signup emails

### ISSUE THREAD

**Issue by wlonk** [lowercasename/sweet#187]
I have a friend who's just tried to sign up and has not gotten any confirmation email. Says he:

> Hey I tried to sign up for sweet.sh, mostly just to check it out. But I haven't been able to get a confirmation email from them (to a gmail email) for a verification token to sign up. Do you know if this is a common problem or there is anyway to contact anyone who might be able to help. There is no way to contact anyone on the webpage... at least not that I can tell.

Just wanted to pass that along, thanks!

(Two friends got no emails, one did.)

**Comment by lowercasename** [comment]
Thanks so much for letting me know, and please send them my apologies! I presume this is a consequence of Gmail not trusting the Sweet email address, and I don’t really have a solution for it, but I’ll have a think! Could you ask them to email me at support@sweet.sh and I’ll manually unlock their accounts?

**Comment by lowercasename** [comment]
I think this now fixed.
