### ISSUE TITLE
All images in user-created posts broken when not logged in

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#19]
Especially egregious wrt to the Very Important Animals community

**Comment by lowercasename** [comment]
This should now be fixed in https://github.com/lowercasename/sweet/pull/22/commits/ca60f14efb3d2521771181e19d9fb36ae56a051f.

**Comment by lowercasename** [comment]
It appears that when I said I’d fixed this, I’d actually done nothing of the sort. Whoops. There’s still a problem where the posts.handlebars partial still isn’t showing the right URLs, despite the updated code in routes.js. Can’t look at it now!

**Comment by lowercasename** [comment]
Oh, I just forgot to attach the right array to the displayed post object - will fix in half an hour when I’m back at my laptop!
