### ISSUE TITLE
When community visibility is changed, the visibility setting of images does not update accordingly

### ISSUE THREAD

**Issue by lowercasename** [lowercasename/sweet#24]
What it says on the tin. Images each get a document in the Images database, and these documents need to be updated when a visibility vote is passed.

**Comment by toBeOfUse** [comment]
What is votes. I go to community editor, I try to change visibility. I click Create Vote it does nothing.

**Comment by toBeOfUse** [comment]
Well, that's in Chrome. In Firefox it sends a post request but the server crashes immediately.

**Comment by toBeOfUse** [comment]
Ok I am working the problem. Chrome was apparently not submitting the form bc it was like "the click event is handled by the thing that disables the button ." In community.handlebars L294.

**Comment by toBeOfUse** [comment]
I guess 52efb77 fixes this. Will test a little more later

**Comment by toBeOfUse** [comment]
This is another thing where if the server is restarted (like if the code is being updated) halfway through the images' privacy properties being changed it'll cause problems. There's probably a better way to do this.

**Comment by lowercasename** [comment]
_Technically_ I always try to soft reset the server, which means it should finish doing whatever database tasks it's doing before it shuts down. In practice I bet this doesn't actually work.
