### ISSUE TITLE
@ mentions don't always work when added with autocomplete

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#27]
I thought it was an end-of-post thing! But it turns out that @ mentions that are put in place with the autocomplete just aren't showing up. If they're at the end of the post.

**Comment by toBeOfUse** [comment]
Because adding an @ mention by clicking on the prompt doesn't trigger an input event and thus doesn't cause the internal representation of the post's contents to update before the send button sends it to the server. I hate when that happens

**Comment by toBeOfUse** [comment]
Hopefully fixed in 7d5d16b, unless that ends up resulting in new and stranger problems. I'll leave this open for a hot second just in case

**Comment by lowercasename** [comment]
This is great, thank you.
