### ISSUE TITLE
Post header w/ username and profile picture can be too wide on mobile

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#3]
When your username is as long as mine is the @ handle on the right of it runs off the screen. Also, sometimes Chrome decides not to display the profile picture with it; the picture is technically loaded, but is displayed with a width of 0 pixels (which is why I think that this is caused by the too wide username formatting thing.) This is not particularly important and is more of a design issue than a technical one so I'm going to leave it alone for a while. Screenshots taken in Chrome Developer Tools emulating the Pixel 2 display (411x731); it also looks the same way on mobile Chrome on my actual phone (an Honor 9 Lite).
![username too wide](https://user-images.githubusercontent.com/49729978/56461306-75821800-637e-11e9-8efd-9049650723b8.jpg)
![profile picture gone](https://user-images.githubusercontent.com/49729978/56461308-77e47200-637e-11e9-8218-a0bbe5fd0bfc.jpg)

**Comment by lowercasename** [comment]
I'm going to leave this as is for now as well - it's better than the username folding over onto a new line. It's still an issue though.
