### ISSUE TITLE
Database indexes

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#31]
I ran a search through this repository's code that looked for createIndex function calls and didn't find any, which leads me to believe that sweet's database is not using any custom indexes. This Is A Mistake, Because Indexes Are Important. An index in MongoDB is just a data structure that stores references to all of the documents in a collection in some specified order. By default, MongoDB uses an index that stores documents in the order of their unique ObjectID, which works well for finding a document by said id because this data structure (a b-tree) can be *very* efficiently searched for documents when you're looking at the field it sorts by. However, it is not so good for our main document retrieval use case: retrieving posts in (roughly) reverse chronological order for feeds. Because ObjectIDs are generated sequentially (they start with an encoding of the timestamp of the moment of their creation), this default index is keeping our post documents sorted in chronological order, which is the exact opposite of the order we're using when we display posts in a feed. This means that every time we retrieve posts for this purpose, the database software has to almost completely reverse the order of the entire posts collection, which, as the website grows, could potentially become *somewhat* computationally expensive.

In order to change this, we can create a new index that sorts the post documents by their lastUpdated timestamp in reverse chronolgical order. This adds a slight overhead to adding a post and to changing a post's lastUpdated field, because that document now has to find its place in this index data structure, but that doesn't compare to having to reverse the order of the entire posts collection every time someone loads their home page. I could have just, like, done this, but instead I decided to write this long, annoying message because I think database internals are interesting and I wanted to create a warning against anyone creating a database bottleneck like our current one again. [The code is quite simple](https://docs.mongodb.com/manual/indexes/); something like `db.posts.createIndex({lastUpdated: -1})`. We could also create other indexes that sort posts by the author and community fields, since we select posts by those fields for those types of individual pages.

**Comment by lowercasename** [comment]
This was a really enjoyable thing to learn about, thank you! I’ve added those indexes to the posts DB; it doesn’t appear that the the ones by author and community are being hit but the reverse lastUpdated one is doing so much work! So cool.

**Comment by lowercasename** [comment]
Shall close this for now. Can open again when/if we need to invent more indexes later.
