### ISSUE TITLE
No comment image previews

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#33]
Problemo is [here](https://github.com/lowercasename/sweet/commit/044696c014b7c52c96e9a9a47b71d3d4e20e100a#diff-b622554c867019a545b4c9ff5a106303R1080) where the image-preview-container is set to hidden by default and then it's unhidden when you click on the text field for making a post but never unhidden in the case of adding images to a comment.

**Comment by lowercasename** [comment]
Whoops.
