### ISSUE TITLE
Rearranging images on iOS also scrolls the page

### ISSUE THREAD

**Issue by lowercasename** [lowercasename/sweet#35]
There is presumably a way to disable scroll when a drag event is ongoing, but currently when I pull an image down, it pulls the page down, and same with up. It’s still possible to rearrange images but only just and only in one direction.

Happens in Safari and Firefox.

**Comment by lowercasename** [comment]
I don’t know why GitHub assigned me to this but let me tell you I am not equipped to fix it!

**Comment by toBeOfUse** [comment]
I mean, neither am I really. Try with 9405aa5 (I just PRed it)
