### ISSUE TITLE
Text formatting drop-up does not appear on iOS

### ISSUE THREAD

**Issue by lowercasename** [lowercasename/sweet#37]
When you select text, nothing happens - only the default iOS widget appears. There are a few threads around medium-editor talking about how to solve it but there doesn’t appear to be a serious solution.

Two solutions are: a static formatting bar comes up on mobile instead, above the text box; the drop down appears below the text on mobile.

Irritating!

**Comment by toBeOfUse** [comment]
that'll happen
![reinvent_the_wheel_2x](https://user-images.githubusercontent.com/49729978/57956701-ece89000-78c7-11e9-813a-160d3c4e0919.png)

**Comment by toBeOfUse** [comment]
I wonder how the actual Medium site handles that. (Probably you're just expected to use the app huh)

**Comment by lowercasename** [comment]
"Writing on Medium is only available on desktop using supported browsers, and on our iOS and Android applications."

Weak!

**Comment by toBeOfUse** [comment]
![Screenshot_20190518-001023](https://user-images.githubusercontent.com/49729978/57964322-7bc5ce80-7901-11e9-87d2-5626ef0592e1.jpg)
not too easy to use it on my Android phone either. I still can technically by tapping blindly on the little bit of black space showing on top there but it's less than ideal

**Comment by toBeOfUse** [comment]
Yeah all the rich text using apps I can think of on my phone have fixed formatting buttons outside of the typing area, presumably specifically to avoid fighting the system text highlight pop up for screen real estate

**Comment by lowercasename** [comment]
Definitely doabale! There appears to be a 'static' option in the settings, and here's a demo: https://yabwe.github.io/medium-editor/static-toolbar.html

**Comment by lowercasename** [comment]
Started work on this here: https://github.com/lowercasename/sweet/pull/39
