### ISSUE TITLE
Cannot add images to a comment on the single post page

### ISSUE THREAD

**Issue by lowercasename** [lowercasename/sweet#38]
I think this is because the code is in the uploadscripts rather than the scripts file. Might be sensible to move code which is shared between comment and post uploads into a separate file?

**Comment by lowercasename** [comment]
Or attach the uploadscripts file to the singleposts page - most of it isn't relevant but that shouldn't matter.

**Comment by toBeOfUse** [comment]
This also applies to user profile pages I guess. Yeah, actually the only part of uploadscripts that won't be relevant is the first 26 lines - the remaining 344 do in fact belong to the image uploader.

**Comment by toBeOfUse** [comment]
Fixed in pull request #40
