### ISSUE TITLE
Reply section displays comments under usernames but mentions are done with handles

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#4]
It's not always clear whose comment an @ mention is aimed at because comments are not displayed with @ handles next to them. In the example below, you have to already know that Jonn Hamm has the handle "johamm" to be sure of the thread of conversation.
![handles vs usernames in reply section](https://user-images.githubusercontent.com/49729978/56461346-2c7e9380-637f-11e9-981c-6152479f77d1.jpg)

**Comment by toBeOfUse** [comment]
Fixed in my latest commit. I don't want to step on any toes here because this is kind of a design issue and that really isn't my field? But this issue genuinely was slowing me down when I joined the site and was trying to read threads.

**Comment by lowercasename** [comment]
It was originally 'if display name exists then show display name and @username, else show @username', but long usernames and display names really messed with the design, so I stripped away the username entirely and added the 'reply' button, which pushes the username into the reply field, but frankly it's not obvious to anyone that's even a button?
