### ISSUE TITLE
What is community double post thing

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#45]
Whatever it is, it should probably fixed as part of #42? I'm assuming it's a backend thing? Not sure what to try to reproduce

**Comment by toBeOfUse** [comment]
just had double post show up on my regular feed. they have two different ids (5ce59095660b8e1f32998a13 and 5ce59095660b8e1f32998a14) so it's not the same post being displayed twice or anything. But they were created at almost exactly the same time?
![image](https://user-images.githubusercontent.com/49729978/58198789-12e1ac00-7c9d-11e9-85c8-0460ff9a56e1.png)

**Comment by toBeOfUse** [comment]
Ok, the first 4 bytes in those ids encode the number of seconds between the post being made and the Unix epoch (00:00:00 UTC, Thursday, 1 January 1970) minus leap seconds, obviously (1,558,548,629 total seconds, in case you were wondering.) That means that the two posts must have been made during the same second. So they could potentially be double-sending a createpost request with fast network speeds, and since @zos is in the UK (you can tell by the time at which they're posting their "end of day" message) and not in Australia that's possible. And I hope that's the case because I just looked at the createpost method and I really don't see how it could be saving duplicate posts, post.save() is called twice and once is after an if and the other is after that if's else.

**Comment by toBeOfUse** [comment]
If those timestamps were identical and were measured in milliseconds like I briefly imagined they were I would have become very scared

**Comment by toBeOfUse** [comment]
Looking at the code in uploadscripts you could probably cause a double post just by clicking on the "Send" button twice (maybe by accident?) before the post request completes and the page reloads. Hopefully that specific problem is fixed in e560076. Maybe that's all that was happening?

**Comment by lowercasename** [comment]
I did defintely just manage to create a double post by hitting the Send button twice fast.

**Comment by toBeOfUse** [comment]
Dare I ask if that was with or without that commit I mentioned? Also, either way the same problem probably has to be patched for leaving comments

**Comment by toBeOfUse** [comment]
Or not? It did/does already have code to disable the button between the comment request being sent and 
the comment request completing, unlike how the poor post form button was

**Comment by lowercasename** [comment]
That was before the commit you mentioned!
