### ISSUE TITLE
Profile pictures not quite displayed square in mobile Chrome

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#48]
![IMG_20190524_150632](https://user-images.githubusercontent.com/49729978/58351075-b82f8800-7e35-11e9-99d0-2660e2825edf.jpg)

Although they do widen to become square for a second if you click on the name next to them (and then you end up on that user's profile page.)

**Comment by lowercasename** [comment]
I can't test this because all browsers on iOS are forced to use the Webkit WebView (yes, I know, Apple are crap), but I suspect it's a flexbox issue and it might be solved by adding `flex-shrink: 0;` to `.postAuthorImage`, which I'll push now.

**Comment by toBeOfUse** [comment]
Excellent, got it in one, at least for my test users' profile pics

**Comment by toBeOfUse** [comment]
The really interesting thing is that this problem was never actually happening to my profile picture, only to everyone else's! I don't know what to do with that information

**Comment by lowercasename** [comment]
> The really interesting thing is that this problem was never actually happening to my profile picture, only to everyone else's! I don't know what to do with that information

Satanic devilry at play? Oh - it's probably to do with the length of the username next to the photo, because there's quite a lot of weird flexbox going on there to allow the text to hide instead of overflowing.

**Comment by toBeOfUse** [comment]
That's very good point

**Comment by toBeOfUse** [comment]
@lowercasename for the record, you could download Chromium and use the smartphone emulator thing there and get a very good idea of what your code will look like on mobile Chrome, although if you don't trust it enough to download it onto your computer (it isn't as heavily vertically integrated as Chrome itself but it is still created by Google) that's probably fair. I wish I could do the same thing with Safari but that hasn't been available for Windows for a long, long time now
