### ISSUE TITLE
When you paste text into the editor, generally bigger font size

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#50]
Don't want to touch this until we figure out which branch of the code we're using, I still vote main branch with that one extra line about touch events and displaying below the highlight, not mobile branch which was like 250 commits behind. Might try to make that work + borrow my brother's old iPad mini to test it

**Comment by toBeOfUse** [comment]
![IMG_20190527_163201](https://user-images.githubusercontent.com/49729978/58438464-06929000-809d-11e9-87c3-f9b9f8e367ef.jpg)
![IMG_20190527_163024](https://user-images.githubusercontent.com/49729978/58438465-072b2680-809d-11e9-8fbf-3f3d4f59db4d.jpg)
zamples

**Comment by lowercasename** [comment]
Definitely the main branch, I have no idea why that discrepancy occured (I do have an idea, I can't use git properly)

**Comment by lowercasename** [comment]
I appear to have fixed this by adding the following into medium-editor's config:

```
paste: {
            forcePlainText: true,
            cleanPastedHTML: true
        }
```
...at some point. Test a bit more and let me know if it happens again?

**Comment by toBeOfUse** [comment]
yeah, this doesn't seem to be a problem anymore. nice
