### ISSUE TITLE
Terrible old posts loading problem

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#51]
I'm like 80% sure this ridiculous problem Lyds is having with seeing old posts is the same one this person had [here](https://stackoverflow.com/questions/22495231/chrome-and-safari-caching-302-redirect) and this person had [here](https://discussions.apple.com/thread/5531657), where after a post request is responded to with a 302 status and a redirect (like our login post request is), the page that the user is being redirected to is being loaded from the browser cache instead of being re-retrieved from the server. The people in the answers solved it by setting some headers in the response, I'm going to throw that in. The best reason to believe that this is being caused by browser caching and not our code being wrong is just that she reported that when this happened, her notifications were old as well (or at least new unread ones weren't showing up on the badge), and there is no plausible mechanism by which she could be getting old notification data directly from the server, there is code to let you scroll back to old posts but not to give you an old version of your notifications, ever. I almost want to make this a separate thing that gets pushed to the server before the rolling logins thing does, so I can ask her if this helps and have hope that this is properly solved.

**Comment by toBeOfUse** [comment]
Headers added in commit 2f51f76

**Comment by toBeOfUse** [comment]
This is also its own thing now: https://github.com/lowercasename/sweet/tree/Set-cache-headers if you feel like merging it and pushing it, just for the hell of it, I bet when you don't have to log in for at least 48 hours it fixes it anyway if this is the cause because browser caches expire by then? I don't know

**Comment by lowercasename** [comment]
Yes for sure will merge and push today! Great sleuthing.

**Comment by lowercasename** [comment]
This is live on the server now!

**Comment by toBeOfUse** [comment]
I'm going to go ahead and call this fixed by the addition of the hashed timestamp to the end of the /showposts request url, great work there @lowercasename
