### ISSUE TITLE
There probably should be an "under maintenance" version of the home page for times like right now

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#58]
Instead of just 502 Bad Gateway. Like, it could just be the Hello World Node.js server script but with HTML saying "sorry come back later" instead of "hello world," and it can be run when the regular server program isn't on. Not that this is going to happen very often anyway

**Comment by lowercasename** [comment]
Agreed. I can actually just do that in my server, and should have done. Next time!

**Comment by lowercasename** [comment]
Also, your name change didn't go through?? Everything else seems great which is amazing. Should I just change it by hand on the server?

**Comment by toBeOfUse** [comment]
Yeah, the process must have exited before that change went through, I should have made it "await" that change like I did all the other (more important) ones, it went through in time when I tested it so I didn't think about that enough

**Comment by toBeOfUse** [comment]
Yeah, you might as well. Or you're pretty safe to rerun that script with "await" in front of line 183 to see if that fixes that and line 122 un-commented out to remove the old boosts field data from the server's database, not that it's hugely important

**Comment by lowercasename** [comment]
Enjoy Your New Identity™

**Comment by toBeOfUse** [comment]
It's the one I've had since 2013 actually

**Comment by toBeOfUse** [comment]
https://giantpredatorymollusk.tumblr.com/archive/2013/11

**Comment by toBeOfUse** [comment]
It was one character too long for your sign up form, though. For fairness I guess that should probably be lengthened for everyone else too. And we were meaning to add a username changing thing for everyone else too, I think, maybe I'll do that next if you're taking the threaded comment thing

**Comment by lowercasename** [comment]
Yeah, go for it!
