### ISSUE TITLE
Comment notifs not disappearing when comments deleted

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#6]
The post https://sweet.sh/bigpredatorymollusk/GXjn1laMV (only viewable to trusted users) has 5 comments by Raphael, but I have 7 notifications indicating new comments from him, but the actual reason for this is that he deleted two comments that he did make, but it turns out he wanted the notifications to disappear for deleted comments. I honestly wouldn't mind leaving it like this to keep people from deleting comments too casually? But if it's an issue it's an issue.
![IMG_20190420_195303](https://user-images.githubusercontent.com/49729978/56463622-f30d4e80-63a5-11e9-8e65-62fe25b56c4a.jpg)

**Comment by lowercasename** [comment]
I agree, I don't mind leaving it like this either.
