### ISSUE TITLE
The new post and user timelines aren't working

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#61]
:(
If you get a second and you can look at the error logs from the server I would be interested to know why

**Comment by toBeOfUse** [comment]
https://sweet.sh/admin/postgraph is sending a request to the server to load the graph itself from /admin/justpostgraph but it looks like it's just left "pending" forever, which makes me suspect that that function is crashing before it can send anything back

**Comment by lowercasename** [comment]
Here we go, this looks like the culprit:

```
4|sweet  | (node:21067) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getFullYear' of undefined
4|sweet  |     at User.find.sort.then (/home/raphael/sweet/app/statisticsTracker.js:273:47)
4|sweet  |     at <anonymous>
4|sweet  |     at process._tickCallback (internal/process/next_tick.js:188:7)
4|sweet  | (node:21067) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)
```

**Comment by toBeOfUse** [comment]
I see... it looks like there are some old users without a stored "joined" date, then.

**Comment by lowercasename** [comment]
Oh. Yes. I... forgot to implement that at the beginning, because I was a fool. There are 62, actually! I think we might be able to do this? https://stackoverflow.com/questions/7327296/how-do-i-extract-the-created-date-out-of-a-mongo-objectid

**Comment by lowercasename** [comment]
Also I am going to bed - please feel welcome to just edit the master branch if you're working on this.

**Comment by toBeOfUse** [comment]
Yeah, I probably should have noticed and questioned the assumption that they would all have that. Beautiful find there, btw.

**Comment by toBeOfUse** [comment]
Alright, I'll merge in my branch where I added a script that'll add joined dates (and timestamps for posts, bc something is causing that version to crash too) to the existing entries and also a version of the graph creator that won't crash if they're missing anyway, just because.
