### ISSUE TITLE
I legitimately can't tell if those lseps in your todayonsweet post are a joke or not

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#63]

**Comment by toBeOfUse** [comment]
![image](https://user-images.githubusercontent.com/49729978/59236179-fa412380-8bc2-11e9-8c1d-09fad7181693.png)

**Comment by lowercasename** [comment]
Not a joke, and they don't come up for me! I had copied it into a native Mac editor and out again, so that's where they must have come from. Medium-editor sure does make more headaches than it solves huh

**Comment by toBeOfUse** [comment]
![reinvent_the_wheel](https://user-images.githubusercontent.com/49729978/59236324-a4b94680-8bc3-11e9-999c-6a2551c1d170.png)

**Comment by lowercasename** [comment]
I am aware you're going to keep sending me that image until we code our own editor, and I'm okay with not acting on that knowledge

**Comment by toBeOfUse** [comment]
Hopefully everyone else assumes they're a joke. But maybe figure out how to filter those characters out, or I guess in theory they should be replaced automatically with <br>s. I'm going to keep sending you that image regardless, we're never going to get rid of all dependencies
