### ISSUE TITLE
Deleted comments still cause a post to be bumped to the top of the feed

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#7]
Yeah.

**Comment by lowercasename** [comment]
Yeah. Currently, the posting API updates the 'lastUpdated' field in the database when a comment is posted. Deleting a comment would require for the lastUpdated field to be set to the timestamp of the previous comment - I can do that this week! A more modular approach could involve a relocatePost function, which would update the lastUpdated field of the post to whichever latest timestamp it can find in the post object. Currently, two things update the timestamp - new comments and the fact that a post was boosted. I can see a strong reason for a post being boosted NOT affecting its (the original post's) timestamp. In future, we should decide if editing a post will update its timestamp, and editing a comment.

**Comment by lowercasename** [comment]
In terms of boosts, if we _do_ update the post's timestamp when it's been boosted, which I'm thinking is dumb the longer I think about it, perhaps there should be a lastBoosted field which the lastUpdated field can pull from in the case of a relocatePost function.

**Comment by lowercasename** [comment]
I've now changed the boost API so it doesn't update the original post's timestamp: https://github.com/lowercasename/sweet/commit/983f098bd255834146ef4c686f744a2c8a21ec74

**Comment by lowercasename** [comment]
This should now be fixed in https://github.com/lowercasename/sweet/pull/26/commits/1fb222825d9b83d772ff376d7d06deda58be05a6 (and hopefully without any new problems emerging).

**Comment by toBeOfUse** [comment]
Extra fixed [here](https://github.com/lowercasename/sweet/pull/28/commits/c9bfdd985b54aeb9c266c47459e1db6bdbe75b85#diff-6db976b763ed71154781e45807c0d4e5R3070). (Added code for the case in which there are no comments remaining after the one that's deleted is deleted.)
