### ISSUE TITLE
Clicking the 'show comments' button doesn't clear 'X mentioned you in their post' notifications

### ISSUE THREAD

**Issue by lowercasename** [lowercasename/sweet#70]
...but it should - in fact it should clear _all_ notifications attached to that post, since that's one of only two vectors to clear notifications so I think we should be more proactive about clearing them, not less

**Comment by toBeOfUse** [comment]
I couldn't reproduce this, it marked the mentioned-by notification read for me. Maybe you fixed this at some point? Or maybe the notifications just weren't refreshed rapidly enough for you to see the change, another consideration for the websockets thing

**Comment by lowercasename** [comment]
This appears to be fine now!
