### ISSUE TITLE
Images sticking to comment box after already being sent once

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#73]
![image](https://user-images.githubusercontent.com/49729978/59638651-5ea13d00-9105-11e9-968c-95de7b1d1f87.png)
![image](https://user-images.githubusercontent.com/49729978/59638657-619c2d80-9105-11e9-9837-76f138bbd4db.png)
Can't seem to reproduce this at all atm, even with the initially trying it with 5 images thing

**Comment by lowercasename** [comment]
This just happened to me! I added an image, then deleted that image, added a different image, submitted the comment, which turned up with the old image (I am not completely convinced I added the different image the second time though), and the old image was stuck in the comment box. I then deleted the comment, deleted the image from the comment box, added the second image again, sent the comment, and then the _second_ image was stuck in the comment box.

**Comment by toBeOfUse** [comment]
Huh. Looking back over that code, I'm vaguely suspicious of my use of "let" instead of "var" in this context, and in fact of the use of "let" in client-side code at all given that [roughly 10% of internet users have a browser that doesn't fully support it](https://caniuse.com/#feat=let) (although in practice, I bet everyone cool enough to be on sweet does.) But, I don't have any concrete ideas except that the code is almost definitely crashing before it gets to [the preview window removing line](https://github.com/lowercasename/sweet/blob/master/views/partials/scripts.handlebars#L249), because, worries about a variable that was declared with let aside, that line seems dead simple and pretty bulletproof. If you see this problem again, it would be lovely if you could open your browser's developer console and see if there's an explanatory error message waiting for you.

Or, if I wanted to get a little clever, I could wrap that section of code in a try-catch block and have it catch exceptions and post-request the details to the server, where they could be saved in some client-side crash log file, publicly accessible at /admin/secretstuff/client-side-crashes.txt. Just for fun I might add that to that one simple pull request that I made to hopefully fix the statistics problem, if I can get any kind of break in the next few days.

**Comment by toBeOfUse** [comment]
Oh shit, you can set window.onerror equal to some function and post every Javascript runtime error ever to happen in a user's browser direct to the server to be put in an error log, why are we/everyone not doing this already, as long as there is not even the remotest possibility of an error in the window.onerror function I guess
