### ISSUE TITLE
Delete comment buttons' hitboxes are real big

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#78]
![hitbox](https://user-images.githubusercontent.com/49729978/59728429-70a6dc80-91e6-11e9-9558-7ea0f0c8ff12.png)
It's not a real problem because of the dialogue that shows up asking you to confirm though

**Comment by lowercasename** [comment]
I guess this gets sorted in the threaded replies update so there's no point fixing it now

**Comment by toBeOfUse** [comment]
Oh shit, sorry, I didn't think of that
