### ISSUE TITLE
Inability to upload pictures without captions

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#8]
This could be on purpose, to stop people from uploading random screenshots and memes en masse without at least having to come up with some half-hearted commentary first, but I think that not every picture needs a caption so I'm putting this here and seeing what happens.

**Comment by lowercasename** [comment]
I guess this doesn't have to be the default, but I'm open to changing it. It would require a small JQuery/JS overhead to remove the 'required' property from the textarea if an image is present in the file upload field, and add it back if the image is removed.
