### ISSUE TITLE
Is there reason that the check for depth before adding reply button to dynamic comments went away

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#80]
Specifically it went away [here](https://github.com/lowercasename/sweet/commit/0b649dc486f15e8cf8a428f5aa317bd601ce6c57#diff-2ae1f9bfb8f379103908b25ced84c769L21). This means that users now get reply buttons in dynamically added comments even if they have a depth greater than 5, although server-side checks mean that if you try to use them the reply will not actually go through. Still, though, the button shouldn't even be there? This is all going to be rewritten for websockets anyway, which I am intrigued by and excited for, but I'm still going to open a pull request for this and a couple of other very small things now.

**Comment by lowercasename** [comment]
Yeah something real weird happened when I was merging, this was my fault

**Comment by lowercasename** [comment]
Fixed!
