### ISSUE TITLE
I clicked on my notifications while viewing /admin/allstats and everyone's icon was a terminator skull

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#82]
Not sure how that happened but I have to admit it's pretty cool

**Comment by lowercasename** [comment]
awwh, I don't get this :(

**Comment by toBeOfUse** [comment]
I don't get it every time either, its ephemeral nature is what makes it so magical. (I think the cause is caught in clientsideerrors.txt, somewhere)
