### ISSUE TITLE
Ok so I see posts in communities including private ones that I'm not in?

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#84]
On the home feed and user profile pages. Private posts' images do correctly 404 though. They're actually marked as public with the normal open eye symbol, and there is no header that says that they're community posts.

I'm very confused, I'm looking through the history of viewingSweet.js to try to find a version of it that didn't do this, to resurrect code from, but I cannot, it looks like it was always (on the home page) [finding all the posts from your followed users](https://github.com/lowercasename/sweet/blob/1e5c45b097a29106090ae02eab56922192e1a2b9/app/viewingSweet.js#L622)  (and joined communities, which isn't relevant here) and then not [setting canDisplay](https://github.com/lowercasename/sweet/blob/1e5c45b097a29106090ae02eab56922192e1a2b9/app/viewingSweet.js#L697)  based on whether any of your followed users' posts are in communities that you're not in, let alone based on whether the community is private, community privacy was actually only checked if you were logged out. I feel like someone should have noticed this before now but here we are. Also, are posts in private communities supposed to also be marked private individually, bc it looks like they aren't? Maybe that changed and is now causing the problem to be visibler?

This shouldn't be that hard to fix, the logic isn't that complicated (just set canDisplay to false if it's a post in a community that you're not in), but I'm baffled as to why I'm only just noticing it, I feel like it wasn't a thing before the threaded comments update (there are instances of this from before then but I didn't notice them then) but I'm not sure what exactly changed... Also I am correct in thinking that when you follow someone you shouldn't get any of their posts that are made in communities that you haven't joined, right? And that also applies when viewing their profile page?

**Comment by lowercasename** [comment]
Oh, that's quite bad! I'm absolutely certain it didn't do it before this update! Posts in private communities were never marked private individually because then they'd only show up for people in that community who are _also_ trusted by the poster, which isn't how it's meant to work. (So they're meant to be public, in short). 

You are correct in that you _only_ get community posts from people you follow if you're in the same community, and that's the same on the profile page.

I'm glad sweet is very quiet at the moment!

**Comment by toBeOfUse** [comment]
what changed, though? i'm reading over showposts in [the original commit of viewingsweet](https://github.com/lowercasename/sweet/blob/1e5c45b097a29106090ae02eab56922192e1a2b9/app/viewingSweet.js) over and over again and I can't find anything that ever stopped this, it must have been something buried in the old posts.handlebars

**Comment by lowercasename** [comment]
oh fuck it _was_, I completely forgot to fix the logic I took out of it! Bollocks!! Right so there were three routes - normal post, community post for a community you're in and community post for a community you're not in - if it's a community you're not in, it hides it entirely. I feel so dumb, I can't believe I forgot to re-implement this!!

**Comment by lowercasename** [comment]
I am currently on the move so if you can fix this I'd be very grateful, i'm a dolt!

**Comment by toBeOfUse** [comment]
Well, don't worry about it too much, large coding projects like these aren't meant to be doable by just one person, and you were counting on me to catch your mistakes (the kind that absolutely anyone doing this kind of thing will fairly frequently make) and I let this go by. I'm going to demonstrate my belief in how trivial this really is by going to bed now, also it's 2:44 am here in Alaska. (Why am I in Alaska?) In theory I have really nothing else to do tomorrow until I get on an airplane to go back home in the middle of the night but I don't know how much time I'll actually get to myself until after that? It might make sense just to move this logic into showposts btw, add another couple of if statements to the canDisplay determining segment, makes sense to clear these unshowable posts out as early in the post displaying pipeline as possible so we don't waste time coming up with recently commented headers and stuff for 'em

**Comment by lowercasename** [comment]
ugh, fixed! I am sure there's a bug or two floating about but in the main, fixed

**Comment by toBeOfUse** [comment]
Regular private posts from users who don't trust me do show up though. Looks like the canDisplay logic originally depended on it being set to false by default and somewhere along the line that got lost. Opening pull request in a sec

**Comment by lowercasename** [comment]
Oh well spotted. Thank you! I didn't think to check and I think almost everyone who I follow trusts me

**Comment by toBeOfUse** [comment]
#85 I guess
