### ISSUE TITLE
The "hide the reply button for dynamic comments if they're too deep" went away again

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#89]
here: https://github.com/lowercasename/sweet/commit/232e29efa8c292391eb4e498cde711becb2cc105#diff-2ae1f9bfb8f379103908b25ced84c769
Pls check this next time, I think your editing software has bug?

**Comment by lowercasename** [comment]
what the actual

**Comment by lowercasename** [comment]
https://github.com/lowercasename/sweet/commit/703a10b95354da06f373d82464a1bb7b41e227af

![image](https://user-images.githubusercontent.com/1748384/59977012-f7333380-95c3-11e9-81db-f2da09adb2a5.png)
