### ISSUE TITLE
Hey I found another "bad gateway" situation

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#98]
Okay so this is an example of a 502 bad gateway problem occurring when you're using a proxy, I discovered it through the proxy that automatically kicks in when you're connected to Starbucks wifi. If you're logged out of sweet and try to navigate to a search page, it sends back a redirect response that attempts to navigate you to "/" (which works perfectly on my normal phone internet), but then when my browser, using the Starbucks proxy, does attempt to fetch sweet.sh/ it gets a 502 bad gateway response, it looks like this:
![image](https://user-images.githubusercontent.com/49729978/60367287-da2fa380-99bb-11e9-956d-950808f71ff7.png)
Note that the request for the sweet.sh/ is going through the proxy's remote IP address, which you can Google, and it turns out it belongs to a data center/web hosting/internet traffic transit thing in Amsterdam. Of course. (The original request to the search page, and also all other interactions with sweet that I can do from here, also go through that IP address, and seem to return the appropriate response just fine.)

It looks like the wifi is sending me through a different remote IP based on where the site I'm going to is hosted? It sends me through Amsterdam to get to sweet but through California to get to pretty much every other site. There must be some reason why this proxy server considers the specific redirect from sweet.sh/search/hellosweet to the home page that you get when you're logged out to be invalid, and gives you a bad gateway error in the middle of it, but lets all other requests go through. MAYBE this is related to the 502 bad gateway response that forestofglory was getting. Not sure how. Frig this

I know that this isn't just a Starbucks thing because when you try to do the above using a free online proxy service like hide.me, it also gives you a 502 bad gateway response, and also it crashes the proxy website.

**Comment by lowercasename** [comment]
but... why.

**Comment by toBeOfUse** [comment]
The redirect for logged out users from "/search/[whatever]" to "/" comes from the isLoggedInOrRedirect function at the bottom of viewingSweet. That function checks res.isAuthenticated() and sends the redirect to "/" response back if you aren't. It then incorrectly calls next("route"), which activates the /:username/:posturl route (as that search url thing technically fits that pattern.) We don't actually need to call next("route") at all after a redirect, because the request has been handled, no other routes are going to be able to do anything.

Node.js does catch this, and throws "NodeError: Cannot set headers after they are sent to the client" in the /:username/:posturl route code (at the part where it tries to send back a 404 response bc it can't find a post matching /search/[whatever], and it throws that bc that can't be done, bc we've already responded to this request.) The fact that Node is catching this (and the fact that this whole thing works fine normally, when you're not using a proxy) makes me doubt that this thing is actually causing a problem, but I have removed next("route") after the redirect code in the "cleanup" pull request.

**Comment by toBeOfUse** [comment]
> The fact that Node is catching this (and the fact that this whole thing works fine normally, when you're not using a proxy) makes me doubt that this thing is actually causing a problem, but I have removed next("route") after the redirect code in the "cleanup" pull request.

Well, I was apparently wrong to doubt that, because this guy does appear to no longer occur.
