### ISSUE TITLE
Emails aren't sending, it says it's missing credentials

### ISSUE THREAD

**Issue by toBeOfUse** [lowercasename/sweet#99]
`Error: Missing credentials for "PLAIN"`! I'm guessing the mailServer export in /config/auth.js is missing on the server, so that the password part isn't getting filled in here:

![image](https://user-images.githubusercontent.com/49729978/60373064-cc364e80-99cc-11e9-91e4-365f0c1da6c2.png)

**Comment by toBeOfUse** [comment]
Or at least I really hope so, I could use an encounter with a simply fixed problem right about now

**Comment by lowercasename** [comment]
Hah, apologies, this is fixed!
